services:
    kasimi.markforumsreadconfirm.listener:
        class: kasimi\markforumsreadconfirm\event\listener
        arguments:
            - @user
            - @template
            - @template_context
        tags:
            - { name: event.listener }
